name: Semantic Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      TEST_API_KEY: ${{ secrets.TEST_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.18.0

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Build docs
        run: npm run docs

      - name: Run semantic-release
        run: npm run semantic-release
